Module failure due to Ansible bug on Manjaro
AttributeError: 'bytes' object has no attribute 'read'

There might be some incompatibility with Manjaro Linux...

Signed-off-by: Minca Daniel Andrei <mandrei17@gmail.com>